<div>
    <strong>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cum delectus incidunt voluptatum aperiam odit
        eveniet a, praesentium officia rem sed? Quis ea quam dolore dolorum repellendus natus perferendis animi
        molestiae?
        Possimus excepturi sed veritatis nostrum. Quibusdam hic doloribus ullam tenetur, earum eaque nam assumenda?
        Dolorem quasi alias saepe deserunt dicta rerum corporis iure magnam sit fuga, voluptatum facilis hic! Eum.
        Earum nulla est ad sed animi aspernatur, neque magnam fuga rem nisi voluptatem quis repellendus exercitationem
        dolore! Alias quia nobis laborum in, ut ducimus, natus doloribus magni deleniti saepe assumenda.
        Atque, obcaecati. Dolorem, harum officia aliquam, magnam rerum voluptatem quod alias ratione inventore ipsa
        molestias suscipit maiores veniam delectus earum placeat laboriosam, consequuntur ab. Et qui omnis vero enim
        autem?</strong>
</div>

<!--
    inject this template in product.info.main container of
    vendor/magento/magento-catalog/view/frontend/layout/catalog_product_view.xml

<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <body>
        <referenceContainer name="product.info.main" >
            <block 
                name="dilevery_message" 
                class="Magento\Framework\View\Element\Template" 
                template="Video21_ViewModels::dilevery_message.phtml" 
                before="product.info.price">
            </block>
        </referenceContainer>    
    </body>
</page>

do the above in layout/catalog_product_view.xml of the current module

-->